---
driver:
  name: vagrant
  provider: vmware_fusion
  
provisioner:
  name: salt_solo
  formula: cis-benchmark
  state_top:
    base:
      '*':
        - cis-benchmark

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
    attributes:
